---
- hosts: all
  tasks:
  - name: ensure libgmp is installed
    apt: pkg=$item state=latest
    with_items: [libgmp-dev, build-essential, libpq-dev]
    sudo: true
  - name: symlink libgmp .so file to libgmp.so
    command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so creates=/usr/lib/libgmp.so
    sudo: true
  - name: symlink libgmp .so file to libgmp.so.3
    command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so.3 creates=/usr/lib/libgmp.so.3
    sudo: true
  roles:
    - common
- hosts: load_balancers
  roles:
    - haproxy
- hosts: static_file_hosts
  roles:
    - static_file_host
- hosts: web_servers
  roles:
    - nginx
    - website

- hosts: message_brokers
  roles:
    - rabbit
- hosts: databases
  roles:
    - postgres
- hosts: search_nodes
  roles:
    - elasticsearch
# - hosts: caches
#  tasks:
#    - include: roles/redis/tasks/add_repository.yml
#    - include: roles/redis/tasks/install_redis.yml
#  roles:
#    - redis
