
- name: ensure libgmp is installed
  apt: pkg=libgmp-dev state=latest

- name: symlink libgmp .so file to libgmp.so
  command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so creates=/usr/lib/libgmp.so

- name: symlink libgmp .so file to libgmp.so.3
  command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so.3 creates=/usr/lib/libgmp.so.3
