---
- name: add redis ppa key
  sudo: true
  apt_key: url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB9316A7BC7917B12"

- name: add redis ppa
  sudo: true
  apt_repository: repo="deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise main"
