---
- name: create logstash user
  user: name=logstash groups=adm

- name: create logstash folder
  file: path=/opt/logstash state=directory group=adm owner=logstash

- name: create logstash configuration folder
  file: path=/etc/logstash/ state=directory owner=logstash

- name: write logstash agent upstart
  template: src=templates/logstash_agent_upstart dest=/etc/init.d/logstash_agent mode=0644 owner=root

- name: write logstash agent config
  template: src=templates/agent.conf dest=/etc/logstash/agent.conf mode=0644 owner=root

- name: Download logstash agent
  get_url: url=https://logstash.objects.dreamhost.com/release/logstash-1.2.1-flatjar.jar dest=/home/logstash/logstash-1.2.1.jar
